# KRM YAML format for TF Blueprint Metadata.
# See https://docs.google.com/document/d/1uMhNixV5RsH3s21pniLZpQDkSLS2cABh2lo1fkq2hMY/edit.
apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-cloud-run-v2-service
  source:
    type: git
    repo: https://github.com/GoogleCloudPlatform/terraform-google-modules.git
    dir: /modules/cloud-run/v2-service # Hypothetical path
  version: 1.0.0
  actuationTool:
    type: Terraform
    versions:
      - ">= 1.3"
  title: Cloud Run V2 Service
  descriptions:
    tagline: A secure and configurable module for deploying containerized applications on Cloud Run V2.
    detailed: This blueprint deploys a Google Cloud Run V2 service with best practices, including options for dedicated service accounts, IAM management, secrets integration, autoscaling, health checks, and VPC connectivity.
  examples:
    - name: simple_service
      location: examples/simple_service
  labels:
    service: run
    platform: gcp
  icon: https://cloud.google.com/images/services/cloud-run/icon-color.svg
  diagrams:
    - name: architecture
      description: A high-level diagram showing the components deployed by this blueprint.
      location: /static/architecture.png # Hypothetical path
  documentations:
    - title: Module Usage
      location: README.md
spec:
  requirements:
    services:
      - run.googleapis.com
      - iam.googleapis.com
      - secretmanager.googleapis.com
      - cloudresourcemanager.googleapis.com
    roles:
      - level: project
        role: roles/run.admin
      - level: project
        role: roles/iam.serviceAccountAdmin
      - level: project
        role: roles/resourcemanager.projectIamAdmin
  variables:
    - name: name
      description: The name of the Cloud Run service.
      type: string
      default: "cloud-run-service-name"
      required: false
    - name: project_id
      description: The Google Cloud project ID to deploy the service to.
      type: string
      default: "gcp-project-id"
      required: false
    - name: location
      description: The Google Cloud location (region) to deploy the service in.
      type: string
      default: "us-central1"
      required: false
    - name: image
      description: The full URL of the container image to deploy. It is recommended to use an image from Artifact Registry.
      type: string
      default: "us-docker.pkg.dev/cloudrun/container/hello"
      required: false
    - name: generate_service_account
      description: If true, a dedicated service account will be created for the Cloud Run service. This is a security best practice.
      type: bool
      default: true
      required: false
    - name: service_account_name
      description: The name of the dedicated service account to create for this service. If `generate_service_account` is true, this name will be used. Must be between 6 and 30 characters.
      type: string
      default: null
      required: false
    - name: service_account_email
      description: The email of an existing service account to use. If `generate_service_account` is false and this is not provided, the default compute service account will be used.
      type: string
      default: null
      required: false
    - name: iam_members
      description: A map of IAM roles to a list of members to grant to the service. For example, to make the service public `{\"roles/run.invoker\" = [\"allUsers\"]}`.
      type: map(list(string))
      default: {}
      required: false
    - name: ingress
      description: Controls who can reach the service. Valid values are INGRESS_TRAFFIC_ALL, INGRESS_TRAFFIC_INTERNAL_ONLY, INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER.
      type: string
      default: "INGRESS_TRAFFIC_ALL"
      required: false
    - name: container_port
      description: The port number that the container listens on for incoming requests.
      type: number
      default: 8080
      required: false
    - name: container_command
      description: Overrides the entrypoint of the container image. If not specified, the container's default entrypoint is used.
      type: list(string)
      default: null
      required: false
    - name: container_args
      description: Arguments to the entrypoint. If not specified, the container's default CMD is used.
      type: list(string)
      default: null
      required: false
    - name: resources
      description: A map defining the CPU and memory limits for the container. Billing is based on allocation, so set these to the minimum required values to optimize costs.
      type: map(string)
      default:
        cpu: "1"
        memory: "512Mi"
      required: false
    - name: env_vars
      description: A map of plaintext environment variables to set in the container. Avoid using this for secrets.
      type: map(string)
      default: {}
      required: false
    - name: secret_env_vars
      description: A map of environment variables sourced from Secret Manager. The key is the environment variable name, and the value is an object with `secret` (the secret name) and `version` (e.g., 'latest'). Note Mounting secrets as volumes is generally more secure.
      type: map(object({ secret = string, version = string }))
      default: {}
      required: false
    - name: secret_volumes
      description: A map to configure secrets to be mounted as files. This is the recommended way to handle secrets. The key is a logical name for the volume, and the value is an object with `secret` (the secret name), `mount_path` (e.g., '/etc/secrets'), and `items` (a map of filename to secret version).
      type: map(object({ secret = string, mount_path = string, items = map(string) }))
      default: {}
      required: false
    - name: scaling
      description: Autoscaling settings for the service. `min_instance_count` should be set to 1 or higher for latency-sensitive applications to avoid cold starts.
      type: object({ min_instance_count = number, max_instance_count = number })
      default:
        min_instance_count: 0
        max_instance_count: 100
      required: false
    - name: max_instance_request_concurrency
      description: The maximum number of concurrent requests that can be sent to a single instance. Tune for I/O-bound (higher) vs. CPU-bound (lower) workloads.
      type: number
      default: 80
      required: false
    - name: startup_cpu_boost
      description: If true, temporarily boosts CPU allocation during instance startup to reduce cold start latency. This is a performance best practice.
      type: bool
      default: true
      required: false
    - name: cpu_idle
      description: If true (default), CPU is only allocated during request processing (request-based billing). If false, CPU is allocated for the entire container instance lifecycle (instance-based billing). Set to false only if reliable background processing is required after a request is served.
      type: bool
      default: true
      required: false
    - name: startup_probe
      description: Configuration for a startup probe to check if the container has started successfully. Essential for applications with slow startup times.
      type: object({ initial_delay_seconds = optional(number), timeout_seconds = optional(number, 1), period_seconds = optional(number, 10), failure_threshold = optional(number, 3), http_get_path = optional(string), tcp_socket_port = optional(number) })
      default: null
      required: false
    - name: liveness_probe
      description: Configuration for a liveness probe to check if the container is still responsive. If the probe fails, the container is restarted. Essential for service reliability.
      type: object({ initial_delay_seconds = optional(number), timeout_seconds = optional(number, 1), period_seconds = optional(number, 10), failure_threshold = optional(number, 3), http_get_path = optional(string) })
      default: null
      required: false
    - name: vpc_access_connector
      description: The full resource ID of the Serverless VPC Access connector to use. Example `projects/my-project/locations/us-central1/connectors/my-connector`.
      type: string
      default: null
      required: false
    - name: vpc_access_egress
      description: The egress setting for VPC outbound traffic. `PRIVATE_RANGES_ONLY` is the recommended default. Use `ALL_TRAFFIC` only if a static egress IP via Cloud NAT is a strict requirement.
      type: string
      default: "PRIVATE_RANGES_ONLY"
      required: false
  variableGroups:
    - name: "Basic Service Configuration"
      description: "Core settings for the Cloud Run service identity and location."
      variables:
        - name
        - project_id
        - location
        - image
    - name: "Service Account & IAM"
      description: "Configure the service identity and access permissions."
      variables:
        - generate_service_account
        - service_account_name
        - service_account_email
        - iam_members
    - name: "Container Configuration"
      description: "Define container-specific settings like ports, resources, and environment."
      variables:
        - container_port
        - container_command
        - container_args
        - resources
        - env_vars
    - name: "Networking & Ingress"
      description: "Control network access to and from the service."
      variables:
        - ingress
        - vpc_access_connector
        - vpc_access_egress
    - name: "Scaling & Performance"
      description: "Adjust autoscaling and CPU allocation for performance and cost optimization."
      variables:
        - scaling
        - max_instance_request_concurrency
        - startup_cpu_boost
        - cpu_idle
    - name: "Secrets Management"
      description: "Securely provide secrets to the application."
      variables:
        - secret_env_vars
        - secret_volumes
    - name: "Health Checks"
      description: "Configure probes to monitor container health and ensure reliability."
      variables:
        - startup_probe
        - liveness_probe
  outputs:
    - name: id
      description: The fully qualified identifier of the Cloud Run service.
    - name: name
      description: The name of the Cloud Run service.
    - name: location
      description: The location where the Cloud Run service is deployed.
    - name: uri
      description: The primary public URI of the Cloud Run service.
    - name: latest_ready_revision
      description: The name of the latest revision of the service that is ready to serve traffic.
    - name: service_account_email
      description: The email of the service account used by the Cloud Run service.
