# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS-IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# TF Blueprint Metadata (https://docs.google.com/document/d/1uMhNixV5RsH3s21pniLZpQDkSLS2cABh2lo1fkq2hMY/edit)
# KRM-style blueprint metadata.
apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-cloud-run-v2-service
  source:
    type: git
    git:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-cloud-run.git
      # A subdirectory of the repo.
      dir: /modules/v2
  version: 1.0.0 # Placeholder version
  actuationTool:
    type: Terraform
    versions:
    - ">= 1.3.0"
spec:
  info:
    title: Cloud Run v2 Service
    icon: # icon is a URL to a 64x64px SVG
      https://cloud.google.com/run/docs/images/run-logo-2022.svg
    # A one-line summary of the blueprint.
    tagline: Deploy a containerized application on Google Cloud Run's Gen2 execution environment.
    descriptions:
      # A detailed description of the blueprint.
      detailed: This blueprint deploys a Google Cloud Run v2 service, offering enhanced performance, concurrency controls, and advanced features like VPC connectors, secret management, and configurable health probes. It is designed for deploying secure, scalable, and cost-effective containerized applications.
    documentations:
    - title: Cloud Run Documentation
      url: https://cloud.google.com/run/docs
    - title: Terraform Module Reference
      url: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_service
    examples:
    - name: simple_service
      location: examples/simple_service
      title: Simple Public Cloud Run Service
  content:
    # List of Terraform variables for the blueprint.
    variables:
    - name: annotations
      description: A map of user-defined annotations to apply to the service and revision. A common annotation is 'run.googleapis.com/cloudsql-instances' to connect to Cloud SQL.
      type: object
      defaultValue: {}
      required: false
    - name: container_args
      description: Arguments to the entrypoint. The docker image's CMD is used if this is not provided.
      type: array
      defaultValue: null
      required: false
    - name: container_command
      description: Entrypoint array. Not executed within a shell. The docker image's ENTRYPOINT is used if this is not provided.
      type: array
      defaultValue: null
      required: false
    - name: container_port
      description: The port number that the container listens on for incoming requests.
      type: number
      defaultValue: 8080
      required: false
    - name: default_uri_disabled
      description: If true, the default `*.run.app` URL is disabled. Recommended when using a custom domain or load balancer with IAP.
      type: boolean
      defaultValue: false
      required: false
    - name: env_vars
      description: A map of plaintext environment variables to set in the container. For secrets, use `secret_env_vars` or `secret_volumes`.
      type: object
      defaultValue: {}
      required: false
    - name: image
      description: The container image to deploy, preferably from Artifact Registry (e.g., 'us-central1-docker.pkg.dev/project-id/repo/image:tag').
      type: string
      defaultValue: us-run.pkg.dev/cloudrun/container/hello
      required: false
    - name: ingress
      description: Controls who can reach the Cloud Run service. Valid values are 'INGRESS_TRAFFIC_ALL', 'INGRESS_TRAFFIC_INTERNAL_ONLY', 'INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER'.
      type: string
      defaultValue: INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER
      required: false
    - name: labels
      description: A map of user-defined labels to organize the service.
      type: object
      defaultValue: {}
      required: false
    - name: liveness_probe
      description: Liveness probe configuration for the container. If the probe fails, the container is restarted. If null, no probe is configured.
      type: object
      defaultValue: null
      required: false
    - name: location
      description: The GCP region where the Cloud Run service will be deployed.
      type: string
      defaultValue: us-central1
      required: false
    - name: max_instance_request_concurrency
      description: The maximum number of concurrent requests an instance can receive.
      type: number
      defaultValue: 80
      required: false
    - name: name
      description: The name of the Cloud Run service.
      type: string
      defaultValue: cloud-run-service-example
      required: false
    - name: project_id
      description: The GCP project ID where the Cloud Run service will be created. If not provided, the provider project will be used.
      type: string
      defaultValue: null
      required: false
    - name: public_access
      description: If true, grants the 'roles/run.invoker' role to 'allUsers', making the service publicly accessible.
      type: boolean
      defaultValue: false
      required: false
    - name: resources
      description: The CPU and memory resource limits for the container. In Cloud Run Gen2, CPU is always allocated. Set to the minimum required to control costs.
      type: object
      defaultValue: {}
      required: false
    - name: scaling
      description: The scaling configuration for the service, including min/max instances.
      type: object
      defaultValue:
        min_instance_count: 0
        max_instance_count: 100
      required: false
    - name: secret_env_vars
      description: A map of environment variables sourced from Secret Manager. The key is the env var name, the value is an object with 'secret' and 'version'.
      type: object
      defaultValue: {}
      required: false
    - name: secret_volumes
      description: A map of secrets to mount as volumes. The key is the volume name. The value specifies mount path, secret name, and a map of items (filename to secret version). This is the most secure method for credentials.
      type: object
      defaultValue: {}
      required: false
    - name: service_account_email
      description: The email address of the dedicated IAM service account to be used by the service's revision. Enforces the principle of least privilege. If not provided, the default compute service account is used.
      type: string
      defaultValue: null
      required: false
    - name: startup_cpu_boost
      description: If true, the container gets a temporary CPU boost during startup, reducing cold start latency.
      type: boolean
      defaultValue: false
      required: false
    - name: startup_probe
      description: Startup probe configuration for the container. Delays the liveness probe until the container has started. Crucial for apps with long startup times. If null, no probe is configured.
      type: object
      defaultValue: null
      required: false
    - name: vpc_access
      description: Configuration for the VPC Access Connector, enabling the service to connect to VPC resources.
      type: object
      defaultValue: null
      required: false
    # Groups of related variables.
    variableGroups:
    - name: Basic Service Configuration
      description: Core settings for the Cloud Run service.
      variables:
      - project_id
      - name
      - location
      - labels
      - annotations
    - name: Container Configuration
      description: Settings related to the container image and its execution environment.
      variables:
      - image
      - container_port
      - container_command
      - container_args
      - resources
    - name: Networking and Access
      description: Controls how the service is accessed and its network connectivity.
      variables:
      - ingress
      - public_access
      - default_uri_disabled
      - vpc_access
    - name: Scaling and Performance
      description: Configure auto-scaling and performance optimizations.
      variables:
      - scaling
      - max_instance_request_concurrency
      - startup_cpu_boost
    - name: Security and Identity
      description: Manage service identity and secrets.
      variables:
      - service_account_email
      - env_vars
      - secret_env_vars
      - secret_volumes
    - name: Health Probes
      description: Configure startup and liveness probes to ensure container health.
      variables:
      - startup_probe
      - liveness_probe
    # List of Terraform outputs for the blueprint.
    outputs:
    - name: id
      description: The fully qualified identifier of the Cloud Run service.
    - name: latest_ready_revision
      description: Name of the latest revision that is serving traffic.
    - name: location
      description: The location where the Cloud Run service was deployed.
    - name: name
      description: The name of the Cloud Run service.
    - name: project
      description: The project ID where the Cloud Run service was deployed.
    - name: uri
      description: The primary public URI of the Cloud Run service.
  # Deployment-time requirements for the blueprint.
  requirements:
    # List of GCP APIs that must be enabled to deploy the blueprint.
    services:
    - run.googleapis.com
    - artifactregistry.googleapis.com
    - secretmanager.googleapis.com
    - vpcaccess.googleapis.com
    - iam.googleapis.com
    # List of IAM roles required to deploy the blueprint.
    roles:
    - role: roles/run.admin
      level: project
      description: Required to create and manage Cloud Run services.
    - role: roles/iam.serviceAccountUser
      level: project
      description: Required to assign a service account to the Cloud Run service.
    - role: roles/secretmanager.secretAccessor
      level: project
      description: Required if using secrets from Secret Manager.
